//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int IdUsuario { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public long NumeroIdentificacion { get; set; }
        public string Email { get; set; }
        public string TipoIdentificacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string nombreCompleto { get; set; }
        public string identificacionFull { get; set; }
    
        public virtual TipoIdentificacion TipoIdentificacion1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
